spring.application.name=paytrack-backend
# DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=Shreyash30


# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
hibernate.transaction.jta.platform =
# Debug (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
